CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255),
    role VARCHAR(32),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS books (
    id BIGSERIAL PRIMARY KEY,
    isbn VARCHAR(255) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    publication VARCHAR(255),
    detail TEXT,
    branch VARCHAR(255),
    price NUMERIC(12,2),
    total_copies INTEGER NOT NULL,
    available_copies INTEGER NOT NULL,
    created_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS book_requests (
    id BIGSERIAL PRIMARY KEY,
    requester_name VARCHAR(255) NOT NULL,
    requested_title VARCHAR(255) NOT NULL,
    requested_author VARCHAR(255),
    note TEXT,
    status VARCHAR(64) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS book_issues (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    book_id BIGINT NOT NULL REFERENCES books(id),
    issued_by_user_id BIGINT REFERENCES users(id),
    issue_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE,
    status VARCHAR(64) NOT NULL
);

-- Ensure IDs auto-generate even on pre-existing tables created by older JPA configs.
ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE book_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE book_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE books ADD COLUMN IF NOT EXISTS cover_path VARCHAR(255); -- relative path to uploaded cover (e.g., /covers/uuid.png)
